### ISSUE TITLE
Keep my Duolingo streak

### ISSUE THREAD

**Issue by dsakura** [rfoel/duolingo#1]
Primeiro, obrigado. Eu consegui rodar a ação de lições, mas este não aparece o botão pra dar inicio. Como que faço? Valeu
![duorun](https://github.com/rfoel/duolingo/assets/4233324/a4539b51-d376-431c-bdb2-31264f8c11a2)

**Comment by rfoel** [comment]
@dsakura pra isso é só usar o workflow `Do a Duolingo lesson`, nele tem a opção de dar início. O `Keep my Duolingo streak` é um cron job que roda todos os dias e faz apenas uma lição para manter o streak.

**Comment by dsakura** [comment]
Perfeito. Muito obrigado
