### ISSUE TITLE
Change Language

### ISSUE THREAD

**Issue by SDragonex** [rfoel/duolingo#10]
Is there any way to change language the bot will farm? for me it only farms xp in russian language even though i only do arabic and english

**Comment by rfoel** [comment]
When the lesson is fetched from Duolingo, you have to provide 2 variables: `fromLanguage` and `learningLanguage`. So let's say you speak `czech` and you're learning `english`, you can change the `index.js` to supply `fromLanguage: "cz"` and `learningLanguage: "en"`, and this will make you farm the language of your choice. These variables are on like ~87 and ~91 from the script if you want to update it yourself.
