### ISSUE TITLE
GitHub actions node update

### ISSUE THREAD

**Issue by Zacktamondo** [rfoel/duolingo#12]
Hello there
The action **Keep my Duolingo streak** not working any more and giving the following error:

> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/setup-node@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

Thank you for the script and your work.

**Comment by rfoel** [comment]
Hey @Zacktamondo, I've updated the actions, thanks!
