### ISSUE TITLE
How To Use

### ISSUE THREAD

**Issue by AirbusOverBoeing** [rfoel/duolingo#2]
Hello I use windows 10 and im new so i dont know how to use?

**Comment by kdssoftware** [comment]
@rfoel This is great repo, but seems the `Usage` in the README is not clear to new users.

Maybe add steps in the README for example: 

```
[How to use](https://github.com/rfoel/duolingo#howtouse)
1. Fork this repository
2. Go to https://www.duolingo.com
3. Open the browser's console
4. Get the JWT token by pasting this in the console, and copy the value ( without `'`)

```js
document.cookie
  .split(';')
  .find(cookie => cookie.includes('jwt_token'))
  .split('=')[1]
 ```
  
  5. Go to your forked repository
  6. Go to Settings > Secrets and Variables > Actions . And click the button `New Repository secret`
  7. For the secret name use `DUOLINGO_JWT` for the secret value use the copied value from step 4.
  8. Go the your forked repository and go the Actions tab and press the button `I understand my workflows, go ahead and enable them`
```

**Comment by rfoel** [comment]
Thanks @kdssoftware, I've merged your PR.
