### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Shasdoww** [rfoel/duolingo#3]
Error when running.
Only happens with certain tokens for somereason, newer accounts seem to be fine.

```Run node index.js
file:///home/runner/work/duolingo/duolingo/index.js:68
      skillId: xpGains.find(xpGain => xpGain.skillId).skillId,
                                                     ^

TypeError: Cannot read properties of undefined (reading 'skillId')
    at file:///home/runner/work/duolingo/duolingo/index.js:6[8](https://github.com/Shasdoww/duolingo/actions/runs/6450025293/job/17508971835#step:4:9):54
    at process.processTicksAndRejections (node:internal/process/task_queues:[9](https://github.com/Shasdoww/duolingo/actions/runs/6450025293/job/17508971835#step:4:10)5:5)

Node.js v18.18.0
Error: Process completed with exit code 1.

**Comment by jamesharding** [comment]
@Shasdoww I see that you managed to get it working for you without making any changes to your repo. How did you manage to get it working? I am having the same issue.

**Comment by ChenyqThu** [comment]
Me too, but my errors look like below:
file:///home/runner/work/duolingo/duolingo/index.js:6[8](https://github.com/ChenyqThu/duolingo/actions/runs/6732029499/job/18297901779#step:4:9)
      skillId: xpGains.find(xpGain => xpGain.skillId).skillId,
                       ^

TypeError: Cannot read properties of undefined (reading 'find')
    at file:///home/runner/work/duolingo/duolingo/index.js:68:24
    at process.processTicksAndRejections (node:internal/process/task_queues:[9](https://github.com/ChenyqThu/duolingo/actions/runs/6732029499/job/18297901779#step:4:10)5:5)

Node.js v18.18.2
Error: Process completed with exit code 1.

**Comment by rfoel** [comment]
`xpGains` is something that is fetched [here](https://github.com/rfoel/duolingo/blob/main/index.js#L12), so it's probably the language you're learning/your account that does not have it. That array of ids is used [here](https://github.com/rfoel/duolingo/blob/main/index.js#L68) for a `skillId`, which is required for the API to work.
You could probably check your network request when you start a new lesson to see how it's done. I've seen this error before with other people but I was never able to replicate it.

**Comment by rfoel** [comment]
@Shasdoww  @jamesharding @ChenyqThu which language are you all learning?

**Comment by rfoel** [comment]
@jamesharding I just started a Portuguese course and I can see already see `xpGains` with one `skillId` in it. I just did the initial lesson. Have you completed any lessons yet?

**Comment by jamesharding** [comment]
I have! I'm 1050 days into the course :) I wonder if there is some A/B testing going on on their end to phase out that lesson structure?

**Comment by rfoel** [comment]
@jamesharding it can be anything really. You can create a custom script following every step your account does on the web, that's how I came up with the current script. Basically there's a http call that fetches a lesson and another one that completes a lesson. In order to fetch a lesson I do some data fetching before, but you should be able to reproduce.

**Comment by Shasdoww** [comment]
> @Shasdoww @jamesharding @ChenyqThu which language are you all learning?

I'm doing Spanish but this is on an old alt account of mine.

**Comment by rfoel** [comment]
That can be a reason. Older accounts might have different payloads.

**Comment by myron27** [comment]
> That can be a reason. Older accounts might have different payloads.

Yes though I've tried it with even older accounts but it still works.

**Comment by 0juni** [comment]
Does this really work? Or is it just a scam

**Comment by rfoel** [comment]
@0juni these are subdomains from duolingo.com

**Comment by 0juni** [comment]
oh ok

**Comment by 0juni** [comment]
It'd be helpful if you made a tutorial

**Comment by Aziz12341234** [comment]
I got the same problem

**Comment by Aziz12341234** [comment]
> Me too, but my errors look like below: file:///home/runner/work/duolingo/duolingo/index.js:6[8](https://github.com/ChenyqThu/duolingo/actions/runs/6732029499/job/18297901779#step:4:9) skillId: xpGains.find(xpGain => xpGain.skillId).skillId, ^
> 
> TypeError: Cannot read properties of undefined (reading 'find') at file:///home/runner/work/duolingo/duolingo/index.js:68:24 at process.processTicksAndRejections (node:internal/process/task_queues:[9](https://github.com/ChenyqThu/duolingo/actions/runs/6732029499/job/18297901779#step:4:10)5:5)
> 
> Node.js v18.18.2 Error: Process completed with exit code 1.

Does yours work now?
