### ISSUE TITLE
Can't run keep my duolingo streak

### ISSUE THREAD

**Issue by VenomousXD** [rfoel/duolingo#5]
While the "Do a Duolingo lesson" tab is available to enable, the "Keep my Duolingo streak" tab doesn't show any button like that. I'm not too advanced with GitHub Actions but, is it supposed to be like that?

**Comment by kdssoftware** [comment]
Its not available in the action tab after forking?
Did you check the last step ( nr 8) ? 
> Go the your forked repository and go the Actions tab and press the button I understand my workflows, go ahead and enable them
