### ISSUE TITLE
Could this get me banned?

### ISSUE THREAD

**Issue by PatatoBit** [rfoel/duolingo#6]
I'd like to use the streak keeper but will could Duo find out that I do? I have a streak on this account that I don't want to lose.

**Comment by rfoel** [comment]
Duolingo has over 74 million active users, I don't think there's a way to get banned here, but I'm no Duolingo employee so there's always a chance. The only way to find out this "hack" exists (it's not even a hack, It's just calling the same endpoints with shortcuts) is if they ever scan the database to find inconsistencies between lessons being completed without the "right" events, but there's no way this ever gonna happen.
