### ISSUE TITLE
Error every time "Keep my Duolingo streak" tries to run

### ISSUE THREAD

**Issue by o800** [rfoel/duolingo#7]
sorry if im being really stupid but how do i fix this?
 
         
Run node index.js
  node index.js
  shell: /usr/bin/bash -e {0}
  env:
    DUOLINGO_JWT: ***
    LESSONS: 1
undefined:1

SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at parseJSONFromBytes (node:internal/deps/undici/undici:4553:19)
    at successSteps (node:internal/deps/undici/undici:4527:27)
    at fullyReadBody (node:internal/deps/undici/undici:1307:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async specConsumeBody (node:internal/deps/undici/undici:4536:7)
    at async file:///home/runner/work/duolingo/duolingo/index.js:20:19

Node.js v18.18.2
Error: Process completed with exit code 1.

**Comment by rfoel** [comment]
Have you set `DUOLINGO_JWT` in GitHub secrets?

**Comment by o800** [comment]
Yes I have.

**Comment by rfoel** [comment]
I have noticed with another account that the [session request](https://github.com/rfoel/duolingo/blob/main/index.js#L20) is breaking sometimes but I don't know what's causing the issue. Unfortunately this is not a product or api, so I can't really give any support, it's just a way I've found to do lessons calling the api directly.

**Comment by ARXChrono** [comment]
It is exactly the same issue for me too, I assume you won't be looking into this as it works for you.

I wonder if a more foolproof way is to store our Duolingo username/password and use Puppeteer to simulate the browser or even write a test with cypress to just fill out the answers.

**Comment by Mothball7205** [comment]
Im having the exact same problem

**Comment by Aziz12341234** [comment]
same
